application: open-module
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /
  login: required
  script: open_module.app

- url: /create
  login: required
  script: open_module.app

- url: /delete
  login: required
  script: open_module.app

- url: /update
  login: required
  script: open_module.app

- url: /list
  login: required
  script: open_module.app

- url: /view
  script: open_module.app

libraries:
- name: jinja2
  version: latest
- name: django
  version: latest
